### ISSUE TITLE
react-adapter failed to unmount: Target container is not a DOM element.

### ISSUE THREAD

**Issue by davidjamesb** [jpinho/svelte-react-material#1]
Thanks for this great utility - it is working correctly so far that my external react components are rendering and behaving correctly, except for the following error message in the console:

**Describe the bug**
```
react-adapter failed to unmount. {
  err: Error: unmountComponentAtNode(...): Target container is not a DOM element.
      at Object.unmountComponentAtNode (C:\Users\User\Desktop\svelte\scaffoldr\node_modules\react-dom\cjs\react-dom.development.js:26123:13)
      at eval (/src/lib/utils/ReactAdapter.svelte:35:34)
      at run (C:\Users\User\Desktop\svelte\scaffoldr\node_modules\svelte\internal\index.js:22:12)
      at Array.forEach (<anonymous>)
      at run_all (C:\Users\User\Desktop\svelte\scaffoldr\node_modules\svelte\internal\index.js:28:9)
      at Object.render (C:\Users\User\Desktop\svelte\scaffoldr\node_modules\svelte\internal\index.js:1686:13)
      at render_response (file:///C:/Users/User/Desktop/svelte/scaffoldr/node_modules/@sveltejs/kit/dist/ssr.js:380:28)
      at async respond$1 (file:///C:/Users/User/Desktop/svelte/scaffoldr/node_modules/@sveltejs/kit/dist/ssr.js:1245:10)
      at async render_page (file:///C:/Users/User/Desktop/svelte/scaffoldr/node_modules/@sveltejs/kit/dist/ssr.js:1290:20)
      at async resolve (file:///C:/Users/User/Desktop/svelte/scaffoldr/node_modules/@sveltejs/kit/dist/ssr.js:1639:10)
```

It appears the `container` is undefined at the point in which `ReactDOM.unmountComponentAtNode(container);` is called.

**Fix**
Using `if(container)` before the call to `ReactDOM.unmountComponentAtNode(container)`. Are there any potential memory-leak issues with this quick fix?

**System Info**

**System:**
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 14.04 GB / 31.94 GB

  **Binaries:**
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD

  **Browsers:**
    Chrome: 92.0.4515.107
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.62)
    Internet Explorer: 11.0.19041.1

  **npmPackages:**
    @sveltejs/kit: next
    svelte: ^3.34.0
    react: ^17.0.2
    react-dom: ^17.0.2
    react-flow-renderer: ^9.6.6

**Comment by jpinho** [comment]
@DJBMASTER what happened to my notifications 🤦 ? I just saw this message.
I gave it a try directly from main with `npm run dev` and I get no console errors.

How are you using the code?! 
Did you forget to `bind:this` to the container? 
Is the component being mounted?

In any case, we can add that assertion there.
Let me push the fix! And thank you, let me know the answers above please 👆

**Comment by jpinho** [comment]
here is your suggestion, let me know if it works ;) 
https://github.com/jpinho/svelte-react/commit/f010f64f737c225854df4bd4950032ed58d00519
